config/routes.rb
Rails.application.routes.draw do
  resources :students
  
  get 'backsystem/index'
  # devise_for :users
  devise_for :users, path: '', path_names: { 
    sign_in: 'login', 
    sign_out: 'logout'
  }

  root to: 'backsystem#index'
  get '/certificate/:id',  to: 'students#certificate', :as => 'pdf_certificate'
  get '/report/:id', to: 'students#report', :as => 'pdf_report'
   get '/laranja1', to: 'students#laranja1', :as => 'laranja1_report'
   get '/l2', to: 'students#l2', :as => 'l2'
   get '/r1', to: 'students#r1', :as => 'r1'
   get '/r2', to: 'students#r2', :as => 'r2'
   get '/v1', to: 'students#v1', :as => 'v1'
   get '/v2', to: 'students#v2', :as => 'v2'
   get '/a1', to: 'students#a1', :as => 'a1'
   get '/a2', to: 'students#a2', :as => 'a2'
    get '/az', to: 'students#az', :as => 'az'
     get '/ve', to: 'students#ve', :as => 've'
  
end

app/models/student.rb
class Student < ApplicationRecord
    
   

    
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  layout 'base/home'
  before_action :authenticate_user!
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all.order(name: :asc)
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_path, notice: 'Student was successfully created.' }
        #format.json { render :index, status: :created, location: @student }
      else
        format.html { render :new }
        #format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to students_path, notice: 'Student was successfully updated.' }
        #format.json { render :index, status: :ok, location: @student }
      else
        format.html { render :edit }
        #format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  def certificate
    @student= Student.find(params[:id])

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: @student.name,
         template: "backsystem/certificate.html.erb",
         layout: "pdf.html",
         # orientation: 'Landscape',
          page_size:    'A4'
       end
    end

  end

  def report
    @student= Student.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
       render pdf: @student.name,
       template: "students/show.html.erb",
       layout: "report.html",
        #orientation: 'Landscape',
        page_size:    'A4'
     end
  end

  end

   def laranja1
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/laranja1.html.erb",
         layout: "FREC/l1.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
  def l2
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/l2.html.erb",
         layout: "FREC/l2.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
   def r1
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/r1.html.erb",
         layout: "FREC/r1.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
   def r2
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/r2.html.erb",
         layout: "FREC/r2.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end

   def v1
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/v1.html.erb",
         layout: "FREC/v1.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
     def v2
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/v2.html.erb",
         layout: "FREC/v2.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end

   def a1
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/a1.html.erb",
         layout: "FREC/a1.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
   def a2
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/a2.html.erb",
         layout: "FREC/a2.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
     def az
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/az.html.erb",
         layout: "FREC/az.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end

    def ve
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/ve.html.erb",
         layout: "FREC/ve.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end



  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :age, :classroom, :father, :mom, :contact, :address, :go, :return,day:[])
    end

    #form_params # => { week_selection: { days: ["0", "Mon", "0", "Tue", "0", "0", "0", "0", "0"] }
end

app/helpers/students_helper.rb
module StudentsHelper
    def checked(area)
        @student.day.nil? ? false : @student.day.match(area)
      end

      def calcularsala(attrib)
        l1 = 0
       
             
               
      
        return l1
        # attrib.each do |s|
        #     if s == "laranja1(2-4)"
        #         l1=l1+1
        #     elsif s == "laranja2(2-4)"
        #         l1=l1+1   
        #     elsif s == "roxo1(5-6)"
        #         l1=l1+1
        #     elsif s == "roxo1(5-6)"  
        #         l1=l1+1
        #     elsif s == 'verde1(7-8)'
        #         l1=l1+1
        #     elsif s == 'verde2(7-8)'
        #         l1=l1+1
        #     elsif s =='amarelo1(9-10)'
        #         l1=l1+1
        #     elsif s =='amarelo2(9-10)'
        #         l1=l1+1
        #     elsif s =='azul(11-12)'
        #         l1=l1+1
        #     elsif s == 'vermelho(13-14)'
        #         l1=l1+1
        #     else
        #     end
        # end
        # l1
    end 
end

app/views/students/_form.html.erb
<div class="col-lg-12">
    <div class="card">
        <div class="card-header"> 
          <% if current_user.email != 'admin@example.com'%>
          <strong>Ficha de Presença</strong>
          <%else%>
          <strong>Ficha de Inscrição</strong>
          <%end%>
        </div>
        <div class="card-body card-block">
                    <!-- form start -->
                    <% if current_user.email != 'admin@example.com'%>
                    <%= form_with(model: student, local: true) do |form| %>

                    <div class="form-group">
                      
                        <%= form.label :"Nome:" %><br>
                        <%= form.text_field :name,class:'form-control' , :readonly => true%>
                      </div>
                    
                    <div class="form-group">
                        <%= form.label :"Presença do Aluno:" %><br>
                      
                      <%= check_box_tag 'student[day][]', 'um', checked('um') %>
                      <%= form.label :"1º Dia:" %><br>
                      
                      <%= check_box_tag 'student[day][]', 'dois', checked('dois') %>
                      <%= form.label :"2º Dia:" %><br>
                      
                      <%= check_box_tag 'student[day][]', 'três', checked('três') %>
                      <%= form.label :"3º Dia:" %><br>
                    </div>
                      
                    <div class="box-footer">
                      <%= form.submit 'Marcar Presença', class:'btn btn-primary' %>
      
                    </div>
                  
                    <% end %>
        </div>
    </div>
</div>

                    <%else%>

                    <%= form_with(model: student, local: true) do |form| %>
                    <% if student.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>
      
                        <ul>
                        <% student.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
      
      
      
      
                    <div class="form-group">
                        <%= form.label :"Presença do Aluno:" %><br>
                      <%#day = ['Mon', 'Tue']%>
                      <%# day.each do |day| %>
                      <%#= form.check_box:day, { multiple: true }, day %>
                      <%# end %>
                      <%#= form.text_field :day,class:'form-control' %>
                      
                      <%= check_box_tag 'student[day][]', 'um', checked('um') %>
                      <%= form.label :"1º Dia:" %><br>
                      
                      <%= check_box_tag 'student[day][]', 'dois', checked('dois') %>
                      <%= form.label :"2º Dia:" %><br>
                      
                      <%= check_box_tag 'student[day][]', 'três', checked('três') %>
                      <%= form.label :"3º Dia:" %><br>
                    </div>
                        
                      <div class="form-group">
                      
                          <%= form.label :"Nome:" %><br>
                          <%= form.text_field :name,class:'form-control' %>
                        </div>
                      
      
                        
      
                        <div class="form-group">
                          <%= form.label :"Idade:" %><br>
                          <%= form.number_field :age,class:'form-control' %>
                        </div>
      
      
                       
      
                        <div class="form-group">
                          <%= form.label :"Sala de aula:" %><br>
                           <%= select("student", "classroom", ['laranja1(2-4)', 'laranja2(2-4)','roxo1(5-6)','roxo2(5-6)','verde1(7-8)','verde2(7-8)','amarelo1(9-10)','amarelo2(9-10)','azul(11-12)','vermelho(13-14)'], { include_blank: true },class:'form-control') %>
                          </div>
                        
                         
                        <div class="form-group">
                          <%= form.label :"Nome do Pai:" %><br>
                          <%= form.text_field :father,class:'form-control' %>
                        </div>
                      
                        <div class="form-group">
                          <%= form.label :"Nome da Mãe:" %><br>
                          <%= form.text_field :mom ,class:'form-control'%>
                        </div>
                      
                      
                        <div class="form-group">
                          <%= form.label :"Telefone para contato:" %><br>
                          <%= form.text_field :contact,class:'form-control' %>
                        </div>
                      
      
                      
                        <div class="form-group">
                          <%= form.label :"Endereço:" %><br>
                          <%= form.text_field :address ,class:'form-control'%>
                        </div>
                      
                      
                        <div class="form-group">
                          <%= form.label :"Como Vai:" %><br>
                          <%= select("student", "go", ['Pais', 'Sozinho(a)','Outro'], { include_blank: true },class:'form-control') %>
                        </div>
                      
                      
                        <div class="form-group">
                          <%= form.label :"Como Volta:" %><br>
                           <%= select("student", "return", ['Pais', 'Sozinho(a)','Outro'], { include_blank: true },class:'form-control') %>
                        </div>
                      
                     
                    <div class="box-footer">
                      <%= form.submit 'Inscrever', class:'btn btn-primary' %>
      
                    </div>
                  
                    <% end %>
        </div>
    </div>
</div>



  

 



                    <% end %>
                  

app/views/students/edit.html.erb
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <% if current_user.email == "admin@example.com" %>
                        <h1>  Editar Aluno :</h1>
                        <%else%>
                        <h1> Aluno :</h1>
                        <% end %>
                        
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li>
                              <%= link_to 'Voltar', students_path,class:"btn btn-primary" %>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="animated fadeIn">


        <div class="row">
          
     
        
  
				<%= render 'form', student: @student %>




     

    </div>


</div><!-- .animated -->
</div>

app/views/students/index.html.erb
<p id="notice"><% notice %></p>
<% if current_user.email == 'admin@example.com'%> 
    <div class="breadcrumbs">
        <div class="breadcrumbs-inner">
            <div class="row m-0">
                <div class="col-sm-4">
                    <div class="page-header float-left">
                        <div class="page-title">
                            <h1>  Alunos Inscritos :</h1>
                        </div>
                    </div>
                </div>
               
                <div class="col-sm-8">
                    <div class="page-header float-right">
                        <div class="page-title">
                            <ol class="breadcrumb text-right">
                                <li> <%= link_to 'Novo aluno', new_student_path,class:"btn btn-primary" %></li>
                            </ol>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <%end%>
    <div class="content">
        <div class="animated fadeIn">
            <div class="row">

                <div class="col-xl-12">
                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title">Alunos: </strong>
                        </div>
                        <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                <% if current_user.email != 'admin@example.com'%>  

                                <thead>
                                        <tr>
                                          <th>Nome :</th>
                                         
                                          <th></th>
                                      
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% @students.each do |student| %>
                                        <% if  current_user.classroom == student.classroom%>
                                            <tr>
                                                <td><%= student.name %></td>
                                               
                                                <!-- <td><%#= link_to 'Visualizar', student ,class:'btn btn-primary'%></td> -->
                                                <td><%= link_to 'Frequência', edit_student_path(student)  ,class:'btn btn-primary'%></td>
                                                
                                              </tr>
                                        <% end %>
                                       
                                      <% end %>
                                    </tbody>
                                

                                <%else%>

                                <thead>
                                        <tr>
                                          <th>Nome :</th>
                                          <th>Idade</th>
                                          <th>Sala</th>
                                         
                                          <th>Certificados</th>
                                     
                                          <th>Ficha de Inscrição</th>
                                          
                                          <th></th>
                                          <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% @students.each do |student| %>
                                        <tr>
                                          <td><%= student.name %></td>
                                          <td><%= student.age %></td>
                                          <td><%= student.classroom %></td>
                                          <% if  student.day ==  "[\"um\", \"dois\"]"%>
                                          <td> <%= link_to 'PDF',pdf_certificate_path(student.id, :format => :pdf), target:'_blank',class:'btn btn-outline-success'%></td>
                                          <%elsif student.day ==  "[\"um\", \"três\"]" %>
                                          <td> <%= link_to 'PDF',pdf_certificate_path(student.id, :format => :pdf), target:'_blank',class:'btn btn-outline-success'%></td>
                                          <%elsif student.day ==  "[\"dois\", \"três\"]" %>
                                          <td> <%= link_to 'PDF',pdf_certificate_path(student.id, :format => :pdf), target:'_blank',class:'btn btn-outline-success'%></td>
                                          <%elsif student.day ==  "[\"um\", \"dois\", \"três\"]" %>
                                          <td> <%= link_to 'PDF',pdf_certificate_path(student.id, :format => :pdf), target:'_blank',class:'btn btn-outline-success'%></td>
                                          <%else%>
                                          <td>Não possui Certificado</td>
                                          <% end %>
                                            
                                            <td> <%= link_to 'PDF',pdf_report_path(student.id, :format => :pdf), target:'_blank',class:'btn btn-outline-success'%></td>
                                          <!-- <td><%#= link_to 'Visualizar', student ,class:'btn btn-primary'%></td> -->
                                          <td><%= link_to 'Editar', edit_student_path(student)  ,class:'btn btn-primary'%></td>
                                          <td><%= link_to 'Deletar', student, method: :delete, data: { confirm: 'Deseja realmente deletar'} ,class:'btn btn-danger' %></td>
                                        </tr>
                                      <% end %>
                                    </tbody>

                                <% end %>
                               
                            </table>
                        </div>
                    </div>
                </div>


            </div>
        </div><!-- .animated -->
    </div><!-- .content -->

app/views/students/new.html.erb
<div class="breadcrumbs">
    <div class="breadcrumbs-inner">
        <div class="row m-0">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Novo Aluno :</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                          <li>
                              <%= link_to 'Voltar', students_path,class:"btn btn-primary" %>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="content">
    <div class="animated fadeIn">


        <div class="row">
          
     
        
  
				<%= render 'form', student: @student %>




     

    </div>


</div><!-- .animated -->
</div>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @student.age %>
</p>

<p>
  <strong>Sala de Aula:</strong>
  <%= @student.classroom %>
</p>

<p>
  <strong>Nome do Pai:</strong>
  <%= @student.father %>
</p>

<p>
  <strong>Nome da Mãe:</strong>
  <%= @student.mom %>
</p>

<p>
  <strong>Contato:</strong>
  <%= @student.contact %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @student.address %>
</p>

<p>
  <strong>Como vai:</strong>
  <%= @student.go %>
</p>

<p>
  <strong>Como volta:</strong>
  <%= @student.return %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>