config/routes.rb
Rails.application.routes.draw do
  resources :students
  
  get 'backsystem/index'
  # devise_for :users
  devise_for :users, path: '', path_names: { 
    sign_in: 'login', 
    sign_out: 'logout'
  }

  root to: 'backsystem#index'
  get '/certificate/:id',  to: 'students#certificate', :as => 'pdf_certificate'
  get '/report/:id', to: 'students#report', :as => 'pdf_report'
   get '/laranja1', to: 'students#laranja1', :as => 'laranja1_report'
   get '/l2', to: 'students#l2', :as => 'l2'
   get '/r1', to: 'students#r1', :as => 'r1'
   get '/r2', to: 'students#r2', :as => 'r2'
   get '/v1', to: 'students#v1', :as => 'v1'
   get '/v2', to: 'students#v2', :as => 'v2'
   get '/a1', to: 'students#a1', :as => 'a1'
   get '/a2', to: 'students#a2', :as => 'a2'
    get '/az', to: 'students#az', :as => 'az'
     get '/ve', to: 'students#ve', :as => 've'
  
end

app/controllers/backsystem_controller.rb
class BacksystemController < ApplicationController
  layout 'base/home'
  before_action :authenticate_user!
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  def index
    @students = Student.all 
  end
  
   def laranja1
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/laranja1.html.erb",
         layout: "FREC/l1.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
  def l2
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/l2.html.erb",
         layout: "FREC/l2.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
   def r1
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/r1.html.erb",
         layout: "FREC/r1.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
   def r2
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/r2.html.erb",
         layout: "FREC/r2.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end

   def v1
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/v1.html.erb",
         layout: "FREC/v1.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
     def v2
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/v2.html.erb",
         layout: "FREC/v2.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end

   def a1
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/a1.html.erb",
         layout: "FREC/a1.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
   def a2
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/a2.html.erb",
         layout: "FREC/a2.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end
     def az
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/az.html.erb",
         layout: "FREC/az.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end

    def ve
     @student= Student.all

      respond_to do |format|
        format.html
        format.pdf do
         render pdf: 'frequencia',
         template: "backsystem/frec/ve.html.erb",
         layout: "FREC/ve.html",
          #orientation: 'Landscape',
          page_size:    'A4'
       end
      end
  end

 

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.permit(:name, :age, :classroom, :father, :mom, :contact, :address, :go, :return,day:[])
  end
end

app/helpers/backsystem_helper.rb
module BacksystemHelper
    def checked(area)
        @student.day.nil? ? false : @student.day.match(area)
      end
end

app/views/backsystem/_footer.html.erb
<div class="clearfix"></div>
 <!-- Footer -->
 <footer class="site-footer">
        <div class="footer-inner bg-white">
            <div class="row">
                <div class="col-sm-6">
                    Copyright &copy; 2019 Victor Wilker
                </div>
                <div class="col-sm-6 text-right">
                    Designed by <a href="https://www.instagram.com/victor_wilker/">Victor Wilker</a>
                </div>
            </div>
        </div>
    </footer>

app/views/backsystem/_header.html.erb
 <!-- Header-->
 <header id="header" class="header">
        <div class="top-left">
            <div class="navbar-header">
                <img class="align-content" src="https://efeitodebencao.com/wp-content/uploads/Prancheta-5.png"  height="50" width="50" alt="">
                <a class="navbar-brand hidden" href="./"><img src="/images/logo2.png" alt="Logo"></a> 
                <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>   
            </div>
        </div> 
        <div class="top-right">
            <div class="header-menu">
               
                <div class="user-area dropdown float-right">
                    <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img class="user-avatar rounded-circle"  src="https://efeitodebencao.com/wp-content/uploads/Prancheta-5.png"   alt="User Avatar">
                    </a>

                    <div class="user-menu dropdown-menu">
                        <%= link_to  "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
                        <!-- <a class="nav-link" href="#"><i class="fa fa-power -off"></i>Logout</a> -->
                    </div>
                </div>

            </div>
        </div>
    </header>
    <!-- /#header -->

app/views/backsystem/_sidebar.html.erb
 <% if  current_user.email == 'admin@example.com'%>
<aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
               
                    <li class="active">
                        <%= link_to root_path  do%>
                        <i class="menu-icon fa fa-laptop"></i>
                        <span>EBF 2019</span>
                        <%end%>
    
                    </li>
                    <li class="menu-title"> Menu</li><!-- /.menu-title -->
                    <li><%= link_to students_path do%>
                        <i class="menu-icon fa fa-table"></i>
                        <span>Alunos</span>
                        <%end%>
                    </li>
                 
                   
                   
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside>

    <%else%>



<aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
        
                    <li class="active">
                        <%= link_to root_path  do%>
                        <i class="menu-icon fa fa-laptop"></i>
                        <span>EBF 2019</span>
                        <%end%>
    
                    </li>
                    <li class="menu-title"> Menu</li><!-- /.menu-title -->
                    <li><%= link_to students_path do%>
                        <i class="menu-icon ti-pencil-alt"></i>
                        <span>Frequência</span>
                        <%end%>
                    </li>
                 
                   
                   
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside>

    <% end %>

app/views/backsystem/certificate.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title><%=@student.name%></title>
     <%= stylesheet_link_tag 'pdf'%>
  </head>

  <body id='pdf'>
    <div >
		<h3 id="texto">
			<%=@student.name%>
		</h3>    
    </div>
    
  </body>
</html>

app/views/backsystem/show.html.erb
<!DOCTYPE html>
<html class="no-js">

<head>
    <title>EBF 2019</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= stylesheet_link_tag    'report' %>
    <style>
        .p{
            text-size-adjust: 10px;
        }
    </style>
</head>

<body >

    <div style="margin-left: 100px" class="CT-Table">
      
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <div class="sectionHeader"><h2>Inscrição</h2></div>
        <div class="sectionContent">
            <table>
                <tr>
                    <td><strong>Nome:</strong></td>
                    <td>
                        <p>

                            <%= @student.name %>
                        </p>
                    </td>

                </tr>
                <tr>
                    <td>
                        <strong>Idade:</strong>
                    </td>
                    <td>
                        <p>

                            <%= @student.age %>
                        </p>
                    </td>

                </tr>
                <tr>
                    <td><strong>Sala de Aula:</strong></td>
                    <td>
                        <p>

                            <%= @student.classroom %>
                        </p>
                    </td>

                </tr>
                <tr>
                    <td><strong>Nome do Pai:</strong></td>
                    <td>
                        <p>

                            <%= @student.father %>
                        </p>
                    </td>

                </tr>
                <tr>
                    <td><strong>Nome da Mãe:</strong></td>
                    <td>
                        <p>

                            <%= @student.mom %>
                        </p>
                    </td>

                </tr>

                <tr>
                    <td><strong>Contato:</strong></td>
                    <td>
                        <p>

                            <%= @student.contact %>
                        </p>
                    </td>

                </tr>

                <tr>
                    <td> <strong>Endereço:</strong></td>
                    <td>
                        <p>

                            <%= @student.address %>
                        </p>
                    </td>

                </tr>

                <tr>
                    <td><strong>Como vai:</strong></td>
                    <td>
                        <p>

                            <%= @student.go %>
                        </p>
                    </td>

                </tr>
                <tr>
                    <td><strong>Como volta:</strong></td>
                    <td>
                        <p>

                            <%= @student.return %>
                        </p>
                    </td>

                </tr>
            </table>
        </div>
    </div>
</body>

</html>